
# To run the container, in the same directory where this file is, run the command 'docker-compose up'

version: '3.3'
services:
  db:
    image: mysql/mysql-server:latest
    restart: always
    environment:
      MYSQL_DATABASE: beep-me
      # So you don't have to use root, but you can if you like
      MYSQL_USER: beep-me-user
      # You can use whatever password you like
      MYSQL_PASSWORD: beep-me-password
      # Password for root access
      MYSQL_ROOT_PASSWORD: beep-me-root-password
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - 3306:3306
    expose:
      # Opens port 3306 on the container
      - 3306
      # Where our data will be persisted
    volumes:
      - "./db_data:/var/lib/mysql"
    
  rabbitMq:
    image: rabbitmq:3-management
    hostname: rabbitMQ
    ports:
      - 15672:15672
      - 5672:5672
    container_name: rabbitMQContainer
  
    
  
  # bunk_db:
  #   image: mysql/mysql-server:latest
  #   restart: always
  #   environment:
  #     MYSQL_DATABASE: beep-me-bunk
  #     # So you don't have to use root, but you can if you like
  #     MYSQL_USER: beep-me-bunk-user
  #     # You can use whatever password you like
  #     MYSQL_PASSWORD: beep-me-bunk-password
  #     # Password for root access
  #     MYSQL_ROOT_PASSWORD: beep-me-bunk-root-password
  #   ports:
  #     # <Port exposed> : < MySQL Port running inside container>
  #     - 3307:3306
  #   expose:
  #     # Opens port 3306 on the container
  #     - 3306
  #     # Where our data will be persisted
  #   volumes:
  #     - "./bunk_db_data:/var/lib/mysql"
# Names our volume
# volumes:
#   my-db:
    